// Edit this file to update your identity, hero copy and headline info.
// Nothing here is fabricated — leave a field empty/placeholder if not ready.

export const profile = {
  name: "Paresh",
  // The hero heading, split into two parts so they can be laid out with a
  // controlled gap (see Hero.jsx + .hero__title in styles.css) instead of
  // relying on literal spaces in one string.
  heroTitleParts: ["Hi…", "I'm Paresh."],
  subtitle: "MUSIC LOVER · TRAVELLER · EXPLORER",
  tagline: "Building things. Exploring places. Collecting stories.",

  ctaPrimary: { label: "EXPLORE MY WORLD", href: "#about" },
  ctaSecondary: { label: "MY JOURNEY", href: "#travel" },

  // Shown as the small "Currently" line in the hero. `songs` cycles through
  // in shuffled order, one at a time, fading between each — add/remove/reorder
  // freely. `rotateMs` controls how long each song stays on screen before
  // swapping to the next — currently 15 minutes; set it to 60 * 60 * 1000
  // for hourly instead.
  currently: {
    emoji: "🎧",
    songs: [
      // Your stated favourite ghazals (from the Music section)
      "Chupke Chupke Raat Din — Ghulam Ali",
      "Ranjish Hi Sahi — Mehdi Hassan",
      "Chitthi Na Koi Sandesh — Jagjit Singh",
      "Joshwalon Ko Khabar Kya — Jagjit Singh",
      // Evergreen Hindi 80s/90s hits
      "Papa Kehte Hain — Qayamat Se Qayamat Tak (1988)",
      "Ae Mere Humsafar — Qayamat Se Qayamat Tak (1988)",
      "Jimmy Jimmy Aaja Aaja — Disco Dancer (1982)",
      "Mera Dil Bhi Kitna Pagal Hai — Saajan (1991)",
      "Pehla Nasha — Jo Jeeta Wohi Sikandar (1992)",
      "Chura Ke Dil Mera — Main Khiladi Tu Anari (1994)",
      "Ek Ladki Ko Dekha Toh Aisa Laga — 1942: A Love Story (1994)",
      "Tujhe Dekha To Yeh Jaana Sanam — Dilwale Dulhania Le Jayenge (1995)",
      "Tirchi Topi Wale — Raja Hindustani (1996)",
      "Dil To Pagal Hai — Dil To Pagal Hai (1997)",
      "Jiya Jale — Dil Se (1998)",
      "Kuch Kuch Hota Hai — Kuch Kuch Hota Hai (1998)",
      "Chunari Chunari — Biwi No. 1 (1999)",
      
      // Hindi Evergreen Melodies — 1970s
      "Pal Pal Dil Ke Paas — Blackmail (1973)",
      "Chura Liya Hai Tumne — Yaadon Ki Baaraat (1973)",
      "Teri Bindiya Re — Abhimaan (1973)",
      "Kabhi Kabhie Mere Dil Mein — Kabhie Kabhie (1976)",
      "Main Pal Do Pal Ka Shair Hoon — Kabhie Kabhie (1976)",
      "Tere Bina Zindagi Se — Aandhi (1975)",
      "Tum Aa Gaye Ho Noor Aa Gaya — Aandhi (1975)",
      "Is Mod Se Jaate Hain — Aandhi (1975)",
      "Aap Ki Aankhon Mein Kuch — Ghar (1978)",
      "Tere Bina Jiya Jaye Na — Ghar (1978)",
      "Aane Wala Pal — Gol Maal (1979)",
      "O Saathi Re — Muqaddar Ka Sikandar (1978)",
      "Dil Kya Kare — Julie (1975)",
      "My Heart Is Beating — Julie (1975)",
      "Ek Ajnabee Haseena Se — Ajanabee (1974)",
      "Hum Dono Do Premi — Ajanabee (1974)",
      "Kya Hua Tera Wada — Hum Kisise Kum Naheen (1977)",
      "Bachna Ae Haseeno — Hum Kisise Kum Naheen (1977)",
      "Rimjhim Gire Sawan — Manzil (1979)",
      "Aanewala Pal Janewala Hai — Gol Maal (1979)",

      // Hindi Evergreen Melodies — 1980s
      "Humein Tumse Pyaar Kitna — Kudrat (1981)",
      "Tu Tu Hai Wahi — Yeh Vaada Raha (1982)",
      "Aisa Sama Na Hota — Zameen Aasmaan (1984)",
      "Neele Neele Ambar Par — Kalaakaar (1983)",
      "Pyar Manga Hai Tumhi Se — College Girl (1978)",
      "Chehra Hai Ya Chand Khila Hai — Saagar (1985)",
      "Saagar Kinare — Saagar (1985)",
      "O Maria — Saagar (1985)",
      "Dekho Maine Dekha Hai — Love Story (1981)",
      "Teri Yaad Aa Rahi Hai — Love Story (1981)",
      "Yaad Aa Rahi Hai — Love Story (1981)",
      "Jab Chhaye Mera Jadoo — Lootmaar (1980)",
      "Hothon Se Chhu Lo Tum — Prem Geet (1981)",
      "Dil Kya Cheez Hai — Umrao Jaan (1981)",
      "In Aankhon Ki Masti — Umrao Jaan (1981)",
      "Justuju Jiski Thi — Umrao Jaan (1981)",
      "Zindagi Ki Na Toote Ladi — Kranti (1981)",
      "Dard-E-Dil Dard-E-Jigar — Karz (1980)",
      "Ek Hasina Thi — Karz (1980)",
      "Om Shanti Om — Karz (1980)",
      "Aate Jaate Hanste Gaate — Maine Pyar Kiya (1989)",
      "Dil Deewana — Maine Pyar Kiya (1989)",
      "Kabootar Ja Ja Ja — Maine Pyar Kiya (1989)",
      "Mere Rang Mein Rangne Wali — Maine Pyar Kiya (1989)",
      "Aaja Shaam Hone Aayi — Maine Pyar Kiya (1989)",
      "My Name Is Lakhan — Ram Lakhan (1989)",
      "Tera Naam Liya — Ram Lakhan (1989)",
      "Chandni O Meri Chandni — Chandni (1989)",
      "Mere Hathon Mein — Chandni (1989)",
      "Mitwa — Chandni (1989)",

      // Hindi Evergreen Melodies — 1990s
      "Dil Hai Ki Manta Nahin — Dil Hai Ki Manta Nahin (1991)",
      "Adayein Bhi Hain — Dil Hai Ki Manta Nahin (1991)",
      "Tu Pyaar Hai Kisi Aur Ka — Dil Hai Ki Manta Nahin (1991)",
      "Dheere Dheere Se Meri Zindagi Mein Aana — Aashiqui (1990)",
      "Nazar Ke Samne — Aashiqui (1990)",
      "Ab Tere Bin — Aashiqui (1990)",
      "Jaane Jigar Jaaneman — Aashiqui (1990)",
      "Bas Ek Sanam Chahiye — Aashiqui (1990)",
      "Main Duniya Bhula Doonga — Aashiqui (1990)",
      "Saanson Ki Zaroorat Hai — Aashiqui (1990)",
      "Bahut Pyar Karte Hain — Saajan (1991)",
      "Tu Shayar Hai — Saajan (1991)",
      "Dekha Hai Pehli Baar — Saajan (1991)",
      "Jeeye To Jeeye Kaise — Saajan (1991)",
      "Tu Hi Re — Bombay (1995)",
      "Kehna Hi Kya — Bombay (1995)",
      "Humma Humma — Bombay (1995)",
      "Mera Chand Mujhe — Mr. Aashiq (1996)",
      "Aankhon Mein Base Ho Tum — Takkar (1995)",
      "Ho Nahi Sakta — Diljale (1996)",
      "Mera Mulk Mera Desh — Diljale (1996)",
      "Ishq Bina — Taal (1999)",
      "Ramta Jogi — Taal (1999)",
      "Nahin Saamne — Taal (1999)",
      "Aankhon Se Tune Kya — Ghulam (1998)",
      "Aati Kya Khandala — Ghulam (1998)",
      "Pehli Pehli Baar Mohabbat Ki Hai — Sirf Tum (1999)",
      "Dilbar Dilbar — Sirf Tum (1999)",
      "Chand Se Parda Kijiye — Aao Pyaar Karen (1994)",
      "Mujhe Neend Na Aaye — Dil (1990)",
      "Hum Pyar Karne Wale — Dil (1990)",
      "Khambe Jaisi Khadi Hai — Dil (1990)",
      "Ruk Ja O Dil Deewane — Dilwale Dulhania Le Jayenge (1995)",
      "Ho Gaya Hai Tujhko To Pyar Sajna — DDLJ (1995)",
      "Zara Sa Jhoom Loon Main — DDLJ (1995)",
      "Mehndi Laga Ke Rakhna — DDLJ (1995)",
      "Mere Khwabon Mein — DDLJ (1995)",
      "Bholi Si Surat — Dil To Pagal Hai (1997)",
      "Are Re Are — Dil To Pagal Hai (1997)",
      "Koi Ladki Hai — Dil To Pagal Hai (1997)",
      "Le Gayi — Dil To Pagal Hai (1997)",
      "Chand Ne Kuch Kaha — Dil To Pagal Hai (1997)",
      "Aankhon Ki Gustakhiyan — Hum Dil De Chuke Sanam (1999)",
      "Nimbooda — Hum Dil De Chuke Sanam (1999)",
      "Tadap Tadap — Hum Dil De Chuke Sanam (1999)",

      // Hindi Melodies — 2000 to 2009
      "Kaho Naa Pyaar Hai — Kaho Naa... Pyaar Hai (2000)",
      "Na Tum Jaano Na Hum — Kaho Naa... Pyaar Hai (2000)",
      "Pyaar Ki Kashti Mein — Kaho Naa... Pyaar Hai (2000)",
      "Dil Ne Yeh Kaha Hai Dil Se — Dhadkan (2000)",
      "Tum Dil Ki Dhadkan Mein — Dhadkan (2000)",
      "Aksar Is Duniya Mein — Dhadkan (2000)",
      "Humko Humise Chura Lo — Mohabbatein (2000)",
      "Aankhein Khuli — Mohabbatein (2000)",
      "Chalte Chalte — Mohabbatein (2000)",
      "Soni Soni — Mohabbatein (2000)",
      "Mitwa — Kabhi Alvida Naa Kehna (2006)",
      "Tumhi Dekho Naa — Kabhi Alvida Naa Kehna (2006)",
      "Suraj Hua Maddham — Kabhi Khushi Kabhie Gham (2001)",
      "You Are My Soniya — Kabhi Khushi Kabhie Gham (2001)",
      "Bole Chudiyan — Kabhi Khushi Kabhie Gham (2001)",
      "Kabhi Khushi Kabhie Gham — Kabhi Khushi Kabhie Gham (2001)",
      "Tere Liye — Veer-Zaara (2004)",
      "Main Yahaan Hoon — Veer-Zaara (2004)",
      "Do Pal — Veer-Zaara (2004)",
      "Aisa Des Hai Mera — Veer-Zaara (2004)",
      "Kal Ho Naa Ho — Kal Ho Naa Ho (2003)",
      "Kuch To Hua Hai — Kal Ho Naa Ho (2003)",
      "Pretty Woman — Kal Ho Naa Ho (2003)",
      "Maahi Ve — Kal Ho Naa Ho (2003)",
      "Tum Se Milke Dil Ka — Main Hoon Na (2004)",
      "Gori Gori — Main Hoon Na (2004)",
      "Chand Sifarish — Fanaa (2006)",
      "Mere Haath Mein — Fanaa (2006)",
      "Des Rangila — Fanaa (2006)",
      "Tere Bina — Guru (2007)",
      "Barso Re — Guru (2007)",
      "Jaage Hain — Guru (2007)",
      "Ajab Si — Om Shanti Om (2007)",
      "Main Agar Kahoon — Om Shanti Om (2007)",
      "Dard-E-Disco — Om Shanti Om (2007)",
      "Tum Se Hi — Jab We Met (2007)",
      "Aaoge Jab Tum — Jab We Met (2007)",
      "Yeh Ishq Hai — Jab We Met (2007)",
      "Mauja Hi Mauja — Jab We Met (2007)",
      "Zara Sa — Jannat (2008)",
      "Haan Tu Hain — Jannat (2008)",
      "Judaai — Jannat (2008)",
      "Khuda Jaane — Bachna Ae Haseeno (2008)",
      "Lucky Boy — Bachna Ae Haseeno (2008)",
      "Pehli Nazar Mein — Race (2008)",
      "Zara Zara Touch Me — Race (2008)",
      "Tera Hone Laga Hoon — Ajab Prem Ki Ghazab Kahani (2009)",
      "Tu Jaane Na — Ajab Prem Ki Ghazab Kahani (2009)",
      "Prem Ki Naiyya — Ajab Prem Ki Ghazab Kahani (2009)",
      "Pehli Baar Mohabbat — Kaminey (2009)",
      "Dhan Te Nan — Kaminey (2009)",

      // Hindi Melodies — 2010 to 2015
      "Pee Loon — Once Upon a Time in Mumbaai (2010)",
      "Tum Jo Aaye — Once Upon a Time in Mumbaai (2010)",
      "Tujhe Bhula Diya — Anjaana Anjaani (2010)",
      "Aas Paas Khuda — Anjaana Anjaani (2010)",
      "Anjaana Anjaani Ki Kahani — Anjaana Anjaani (2010)",
      "Teri Meri — Bodyguard (2011)",
      "I Love You — Bodyguard (2011)",
      "Desi Beat — Bodyguard (2011)",
      "Saans — Jab Tak Hai Jaan (2012)",
      "Heer — Jab Tak Hai Jaan (2012)",
      "Challa — Jab Tak Hai Jaan (2012)",
      "Ishq Shava — Jab Tak Hai Jaan (2012)",
      "Tum Hi Ho — Aashiqui 2 (2013)",
      "Chahun Main Ya Naa — Aashiqui 2 (2013)",
      "Sunn Raha Hai — Aashiqui 2 (2013)",
      "Bhula Dena — Aashiqui 2 (2013)",
      "Milne Hai Mujhse Aayi — Aashiqui 2 (2013)",
      "Kabira — Yeh Jawaani Hai Deewani (2013)",
      "Badtameez Dil — Yeh Jawaani Hai Deewani (2013)",
      "Subhanallah — Yeh Jawaani Hai Deewani (2013)",
      "Ilahi — Yeh Jawaani Hai Deewani (2013)",
      "Dilliwaali Girlfriend — Yeh Jawaani Hai Deewani (2013)",
      "Balam Pichkari — Yeh Jawaani Hai Deewani (2013)",
      "Samjhawan — Humpty Sharma Ki Dulhania (2014)",
      "Saturday Saturday — Humpty Sharma Ki Dulhania (2014)",
      "Main Tenu Samjhawan Ki — Humpty Sharma Ki Dulhania (2014)",
      "Galliyan — Ek Villain (2014)",
      "Banjaara — Ek Villain (2014)",
      "Zaroorat — Ek Villain (2014)",
      "Humdard — Ek Villain (2014)",
      "Mast Magan — 2 States (2014)",
      "Locha-E-Ulfat — 2 States (2014)",
      "Iski Uski — 2 States (2014)",
      "Manwa Laage — Happy New Year (2014)",
      "India Waale — Happy New Year (2014)",
      "Sooraj Dooba Hain — Roy (2015)",
      "Tu Hai Ki Nahi — Roy (2015)",
      "Chittiyaan Kalaiyaan — Roy (2015)",
      "Gerua — Dilwale (2015)",
      "Janam Janam — Dilwale (2015)",
      "Tukur Tukur — Dilwale (2015)",
      "Agar Tum Saath Ho — Tamasha (2015)",
      "Matargashti — Tamasha (2015)",
      "Heer Toh Badi Sad Hai — Tamasha (2015)",

      // Hindi Melodies — 2016 to 2020
      "Sanam Re — Sanam Re (2016)",
      "Hua Hain Aaj Pehli Baar — Sanam Re (2016)",
      "Bolna — Kapoor & Sons (2016)",
      "Kar Gayi Chull — Kapoor & Sons (2016)",
      "Buddhu Sa Mann — Kapoor & Sons (2016)",
      "Kaun Tujhe — M.S. Dhoni: The Untold Story (2016)",
      "Jab Tak — M.S. Dhoni: The Untold Story (2016)",
      "Besabriyaan — M.S. Dhoni: The Untold Story (2016)",
      "Channa Mereya — Ae Dil Hai Mushkil (2016)",
      "Ae Dil Hai Mushkil — Ae Dil Hai Mushkil (2016)",
      "Bulleya — Ae Dil Hai Mushkil (2016)",
      "The Breakup Song — Ae Dil Hai Mushkil (2016)",
      "Nashe Si Chadh Gayi — Befikre (2016)",
      "Ude Dil Befikre — Befikre (2016)",
      "Enna Sona — OK Jaanu (2017)",
      "The Humma Song — OK Jaanu (2017)",
      "Humsafar — Badrinath Ki Dulhania (2017)",
      "Roke Na Ruke Naina — Badrinath Ki Dulhania (2017)",
      "Aashiq Surrender Hua — Badrinath Ki Dulhania (2017)",
      "Hawayein — Jab Harry Met Sejal (2017)",
      "Phurrr — Jab Harry Met Sejal (2017)",
      "Safar — Jab Harry Met Sejal (2017)",
      "Tera Yaar Hoon Main — Sonu Ke Titu Ki Sweety (2018)",
      "Dil Chori — Sonu Ke Titu Ki Sweety (2018)",
      "Bom Diggy Diggy — Sonu Ke Titu Ki Sweety (2018)",
      "Kaun Nachdi — Sonu Ke Titu Ki Sweety (2018)",
      "Dilbar — Satyameva Jayate (2018)",
      "Paniyon Sa — Satyameva Jayate (2018)",
      "Tera Fitoor — Genius (2018)",
      "Dil Meri Na Sune — Genius (2018)",
      "Pal — Jalebi (2018)",
      "Tum Se — Jalebi (2018)",
      "Mere Naam Tu — Zero (2018)",
      "Husn Parcham — Zero (2018)",
      "Ve Maahi — Kesari (2019)",
      "Teri Mitti — Kesari (2019)",
      "Apna Time Aayega — Gully Boy (2019)",
      "Mere Gully Mein — Gully Boy (2019)",
      "Doori — Gully Boy (2019)",
      "Bekhayali — Kabir Singh (2019)",
      "Kaise Hua — Kabir Singh (2019)",
      "Tujhe Kitna Chahne Lage — Kabir Singh (2019)",
      "Mere Sohneya — Kabir Singh (2019)",
      "Pehla Pyaar — Kabir Singh (2019)",
      "Shayad — Love Aaj Kal (2020)",
      "Mehrama — Love Aaj Kal (2020)",
      "Haan Main Galat — Love Aaj Kal (2020)",
      "Malang — Malang (2020)",
      "Chal Ghar Chalen — Malang (2020)",
      "Phir Na Milen Kabhi — Malang (2020)",

      // Hindi Melodies — 2021 to Present
      "Raataan Lambiyan — Shershaah (2021)",
      "Ranjha — Shershaah (2021)",
      "Mann Bharryaa 2.0 — Shershaah (2021)",
      "Param Sundari — Mimi (2021)",
      "Phir Na Aisi Raat Aayegi — Laal Singh Chaddha (2022)",
      "Kahani — Laal Singh Chaddha (2022)",
      "Tere Hawaale — Laal Singh Chaddha (2022)",
      "Kesariya — Brahmastra (2022)",
      "Deva Deva — Brahmastra (2022)",
      "Rasiya — Brahmastra (2022)",
      "Apna Bana Le — Bhediya (2022)",
      "Thumkeshwari — Bhediya (2022)",
      "Maan Meri Jaan — King (2022)",
      "Heeriye — Jasleen Royal (2023)",
      "Chaleya — Jawan (2023)",
      "Not Ramaiya Vastavaiya — Jawan (2023)",
      "Zinda Banda — Jawan (2023)",
      "Satranga — Animal (2023)",
      "Pehle Bhi Main — Animal (2023)",
      "Hua Main — Animal (2023)",
      "Arjan Vailly — Animal (2023)",
      "O Maahi — Dunki (2023)",
      "Nikle The Kabhi Hum Ghar Se — Dunki (2023)",
      "Lutt Putt Gaya — Dunki (2023)",
      "Tere Vaaste — Zara Hatke Zara Bachke (2023)",
      "Phir Aur Kya Chahiye — Zara Hatke Zara Bachke (2023)",
      "Tum Kya Mile — Rocky Aur Rani Kii Prem Kahaani (2023)",
      "Ve Kamleya — Rocky Aur Rani Kii Prem Kahaani (2023)",
      "What Jhumka? — Rocky Aur Rani Kii Prem Kahaani (2023)",
      "Sajni — Laapataa Ladies (2024)",
      "Akhiyan Gulaab — Teri Baaton Mein Aisa Uljha Jiya (2024)",
      "Laal Peeli Akhiyaan — Teri Baaton Mein Aisa Uljha Jiya (2024)",
      "Tere Sang Ishq Hua — Yodha (2024)",
      "Zaroorat Se Zyada — Vedaa (2024)",
      "Aaj Ki Raat — Stree 2 (2024)",
      "Aayi Nai — Stree 2 (2024)",
      "Tum Se — Teri Baaton Mein Aisa Uljha Jiya (2024)",
      "Ishq Jaisa Kuch — Fighter (2024)",
      "Heer Aasmani — Fighter (2024)",
      "Aavan Jaavan — War 2 (2025)",
      "Sitaare — Ikkis (2025)",
      
      // Telugu Evergreen Melodies
    "Priya Priya — Geethanjali (1989)",
    "Jagada Jagada — Geethanjali (1989)",
    "Andamaina Premarani — Premikudu (1994)",
    "Mukkala Mukabala — Premikudu (1994)",
    "O Papa Lali — Geethanjali (1989)",
    "Yamuna Thatilo — Dalapathi (1991)",
    "Sundari Nuvve — Dalapathi (1991)",
    "Naa Cheli Rojave — Roja (1992)",
    "Paruvam Vanaga — Roja (1992)",
    "Nelluri Nerajana — Oke Okkadu (1999)",
    "Mellisaiye — Mr. Romeo (1996)",
    "Snehithudaa — Sakhi (2000)",
    "Yedo Yedo — Nee Sneham (2002)",
    "Cheppave Chirugali — Okkadu (2003)",
    "Nuvvostanante Nenoddantana — Varsham (2004)",
    "Mellaga Karagani — Varsham (2004)",
    "Nuvvunte — Arya (2004)",
    "Feel My Love — Arya (2004)",
    "Choododde — Pokiri (2006)",
    "Ippatikinka — Pokiri (2006)",
    "Adire Adire — Bommarillu (2006)",
    "Bommani Geesthey — Bommarillu (2006)",
    "Appudo Ippudo — Bommarillu (2006)",
    "Uppenantha — Arya 2 (2009)",
    "Ringa Ringa — Arya 2 (2009)",
    "Nammaka Tappani — Bommarillu (2006)",
    "Vachinde — Fidaa (2017)",
    "Hey Pillagaada — Fidaa (2017)",
    "Inkem Inkem Inkem Kaavaale — Geetha Govindam (2018)",
    "Yenti Yenti — Geetha Govindam (2018)",
    "Undiporaadhey — Husharu (2018)",
    "Samajavaragamana — Ala Vaikunthapurramuloo (2020)",
    "Butta Bomma — Ala Vaikunthapurramuloo (2020)",
    "Nee Kannu Neeli Samudram — Uppena (2021)",
    "Srivalli — Pushpa: The Rise (2021)",
    "Oh Sita Hey Rama — Sita Ramam (2022)",
    "Inthandham — Sita Ramam (2022)",
    "Kaanunna Kalyanam — Sita Ramam (2022)",
    "Priyathama Priyathama — Majili (2019)",
    "Evare — Premam (2016)",
    "Ninnila — Tholi Prema (2018)",
    "Vellipomaakey — Sahasam Swasaga Sagipo (2016)",
    "Adiga Adiga — Ninnu Kori (2017)",
    "Em Sandeham Ledu — Oohalu Gusagusalade (2014)",
    "Chali Chaliga — Mr. Perfect (2011)",
    "Nijanga Nenena — Kotha Bangaru Lokam (2008)",
    "Kalusukovalani — Kalusukovalani (2002)",
    "Cheliya Cheliya — Gharshana (2004)",
    "Naa Hrudayamlo — Manasantha Nuvve (2001)",

    // Marathi Evergreen Melodies
    "Man Udhan Varyache — Aga Bai Arrecha! (2004)",
    "Mala Ved Lagale — Timepass (2014)",
    "Yad Lagla — Sairat (2016)",
    "Sairat Zaala Ji — Sairat (2016)",
    "Aatach Baya Ka Baavarla — Sairat (2016)",
    "Zingaat — Sairat (2016)",
    "Apsara Aali — Natarang (2010)",
    "Khel Mandala — Natarang (2010)",
    "Wajle Ki Bara — Natarang (2010)",
    "Tik Tik Vajate Dokyat — Duniyadari (2013)",
    "Zindagi Zindagi — Duniyadari (2013)",
    "Deva Tujhya Gabharyala — Duniyadari (2013)",
    "Hi Chaal Turu Turu — Ashtavinayak (1979)",
    "Shukratara Mand Wara — Shukratara (1963)",
    "Ya Janmavar Ya Jagnyavar — Umbartha (1982)",
    "Gomu Sangtina Mazya — Ha Khel Savalyancha (1976)",
    "Jeev Rangala — Jogwa (2009)",
    "Morya Morya — Uladhaal (2008)",
    "Kadhi Tu — Mumbai Pune Mumbai (2010)",
    "Saavar Re Mana — Mitwaa (2015)",
    "Sukh Kalale — Ved (2022)",
    "Olya Sanj Veli — Premachi Goshta (2013)",
    "Kitida Navyane — Ti Saddhya Kay Karte (2017)",
    "Jara Jara — Muskurake Dekh Zara (2009)",
    "Mala Jau Dya Na Ghari — Natarang (2010)",
    "Aabhas Ha — Yanda Kartavya Aahe (2006)",
    "Tola Tola — Duniyadari (2013)",
    "Man Mandira — Katyar Kaljat Ghusali (2015)",
    "Sur Niragas Ho — Katyar Kaljat Ghusali (2015)",
    "Phite Andharache Jaale — Natarang (2010)",
    "Rang Maza Vegla — Rang Maza Vegla (1989)",
    "He Surano Chandra Vha — Marathi Bhavgeet",
    "Bhaav Sarvange — Marathi Bhavgeet",
    "Kevha Tari Pahate — Marathi Bhavgeet",
    "Gaarva — Milind Ingle",
    "Saang Na — Marathi Melody",
    "Jeev Pisatala — Marathi Melody",

    // Telugu Classical and Devotional Melodies
    "Jagadananda Karaka — Sri Ramadasu (2006)",
    "Sada Siva Sanyasi — Khadgam (2002)",
    "Annamayya — Annamayya (1997)",
    "Brahmam Okate — Annamayya (1997)",
    "Vinaro Bhagyamu — Annamayya (1997)",
    "Adivo Alladivo — Annamayya (1997)",
    "Om Namah Shivaya — Sagara Sangamam (1983)",
    "Shiv Shankari — Jagadeka Veeruni Katha (1961)",
    "Aakasam Loni — Nuvvostanante Nenoddantana (2005)",
    "Mounamelanoyi — Sagara Sangamam (1983)"
    ],
    rotateMs: 15 * 60 * 1000, // 15 minutes
  },

  location: "India",

  // Leave empty and the UI will render "[Add email]" instead of inventing one.
  email: "choudaryparesh28@gmail.com",
};
