export const workParagraphs = [
  "My journey in technology has been a bit of everything. 😄",
  "I started by learning and working around system administration, troubleshooting and understanding how computers actually work. I was always curious about what is happening behind the screen — not just the software, but the hardware too.",
  "I have a good amount of hands-on knowledge of PCs and laptops, including understanding hardware at the chipset level, troubleshooting issues and even doing repairs. 🔧",
  "That experience helped me build a strong technical foundation. I feel understanding the basics properly always helps, especially when you are trying to figure out why something is not working.",
  "Over time, I moved more towards the software side and currently I'm working as a SNow Developer (freelancing), mainly working with ITSM, ITOM, CSM and HRSD. I have strong hands-on experience in these areas along with relevant certifications. I enjoy working on real-time problems, debugging things and finding a proper solution rather than just making something work somehow. 😄",
  "Apart from ServiceNow, I'm also a DevOps enthusiast. ☁️",
  "I have completed the AWS Solutions Architect – Associate certification and have practical experience working with tools like Jenkins, Docker, Terraform, Ansible and SonarQube.",
  "I've also worked with Python, HTML and YAML, and I keep experimenting with different technologies whenever I get the time. Sometimes it's for work, sometimes just because I got curious about something. 😅",
  "So my technical journey has basically gone from hardware → system administration → software → cloud → DevOps, and I'm still learning and exploring.",
  "I don't want to limit myself to one technology or one area. I like understanding how different things connect with each other and seeing what I can build with them.",
  "Still learning.",
  "Still experimenting.",
  "Still breaking things occasionally. 😂",
  "And hopefully getting a little better with every step.",
  "**That's my journey so far... let's see where it goes next. 🚀**",
];
